Fixed failing boosted content spec
Ran into trouble getting this spec to run:

 1) SuperfreshUrlToIndexedDocument#perform(url, affiliate_id) when the URL points to an HTML page when the page has a HTML title when the page does not have a description meta tag should use the initial subset of non-HTML words of the web page as the description
     Failure/Error: idoc.title.should == "Carribean Sea Regional Atlas - Map Service and Layer..."
     NoMethodError:
       undefined method `title' for nil:NilClass
     # ./spec/models/superfresh_url_to_indexed_document_spec.rb:84

I see this in test.log:

Trouble fetching http://www.ncddc.noaa.gov/interactive-maps/ocean-exploration/oer-caribbean-sea/data-layers.html for boosted content creation: getaddrinfo: nodename nor servname provided, or not known

The URL in the fixture has some sort of problem (server down maybe), so I just changed the test to hit Google, since we’re stubbing the result of the call anyway.